<?php

return [
	'CONSUMER_KEY' => env('TWITTER_CONSUMER_KEY', ''),
	'CONSUMER_SECRET' => env('TWITTER_CONSUMER_SECRET', ''),
	'ACCESS_TOKEN' => env('TWITTER_ACCESS_TOKEN', ''),
	'ACCESS_TOKEN_SECRET' => env('TWITTER_ACCESS_TOKEN_SECRET', ''),
	'CALLBACK_URL' => env('TWITTER_CALLBACK_URL', ''),
];
